# Generated by Django 4.0.6 on 2023-01-24 06:42

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HesabMoaseseh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=10)),
                ('cart_number', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Khayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NUKKNOW', 'Unknown')], default='NUKKNOW', max_length=8)),
                ('creating_date', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Madadjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NUKKNOW', 'Unknown')], default='NUKKNOW', max_length=8)),
                ('creating_date', django_jalali.db.models.jDateField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TahvilgirandehSandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SandoghKhayerieh',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('typee', models.CharField(choices=[('PLASTICB', 'PlasticBig'), ('PLASTICS', 'PlasticBig'), ('FELEZIB', 'FeleziBig'), ('FELEZIS', 'FeleziSmall')], max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NUKKNOW', 'Unknown')], default='NUKKNOW', max_length=8)),
                ('strting_date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('khayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.khayer')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', django_jalali.db.models.jDateField(auto_now=True)),
                ('typee', models.CharField(blank=True, choices=[('CART', 'Cart'), ('CASH', 'Cash'), ('SANDOGH', 'Sandogh')], default='CASH', max_length=7, null=True)),
                ('authority', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=12, null=True)),
                ('has_paid', models.CharField(blank=True, max_length=12, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('khayer_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hesab_moaseseh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.hesabmoaseseh')),
                ('khayer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.khayer')),
                ('sandogh_khayerieh', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.sandoghkhayerieh')),
                ('tahvilgirandeh_sandogh', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.tahvilgirandehsandogh')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Helping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', django_jalali.db.models.jDateField(auto_now=True)),
                ('hesab_moaseseh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.hesabmoaseseh')),
                ('madadjo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.madadjo')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('sandogh_khayerieh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.sandoghkhayerieh')),
                ('tavilgirandeh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.tahvilgirandehsandogh')),
            ],
        ),
    ]
