# Generated by Django 4.0.4 on 2023-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khayer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=8),
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNKNOWN', 'Unknown'), ('ARCHIVE', 'Archive')], default='UNKNOWN', max_length=8),
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='typee',
            field=models.CharField(choices=[('PLASTICB', 'Plastic-Bozorg'), ('PLASTICS', 'Plastic-kochak'), ('FELEZIB', 'Felezi-Bozorg'), ('FELEZIS', 'Felezi-kochak')], max_length=8),
        ),
    ]
