# Generated by Django 4.0.4 on 2023-05-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_khayer_status_alter_sandoghkhayerieh_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khayer',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='khayer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('UNKNOWN', 'نامشخص')], default='UNKNOWN', max_length=8),
        ),
        migrations.AlterField(
            model_name='madadjo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('UNKNOWN', 'نامشخص')], default='UNKNOWN', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='typee',
            field=models.CharField(blank=True, choices=[('CART', 'کارت'), ('CASH', 'پول نقد'), ('SANDOGH', 'صندوق خیریه')], default='CASH', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیر فعال'), ('UNKNOWN', 'مشخص'), ('ARCHIVE', 'آرشیو')], default='UNKNOWN', max_length=8),
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='typee',
            field=models.CharField(choices=[('PLASTICB', 'پلاستیکی بزرگ'), ('PLASTICS', 'پلاستیکی کوچک'), ('FELEZIB', 'فلزی بزرگ'), ('FELEZIS', 'فلزی کوچک')], max_length=8),
        ),
    ]
