# Generated by Django 4.0.4 on 2023-05-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_khayer_home_phone_number_alter_khayer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandoghkhayerieh',
            name='last_khayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_sandoghkhayeriehs', to='management.khayer'),
        ),
        migrations.AlterField(
            model_name='khayer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('UNKNOWN', 'نامشخص')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='madadjo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('UNKNOWN', 'نامشخص')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='khayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandoghkhayeriehs', to='management.khayer'),
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیر فعال'), ('UNKNOWN', 'مشخص'), ('ARCHIVE', 'آرشیو')], default='ACTIVE', max_length=8),
        ),
    ]
