# Generated by Django 4.0.4 on 2023-05-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_sandoghkhayerieh_last_khayer_alter_khayer_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandoghkhayerieh',
            old_name='last_khayer',
            new_name='khayer_ghabli',
        ),
    ]
